In [1]:
import pandas as pd
import csv

In [2]:
themoviedb_data = 'TheSilverScreenProject/TheMoviedb_query/Mergedquery_clean.csv'
omdb_data = 'TheSilverScreenProject/OMDb_Data/OMDb_Query.csv'

tmdb_df = pd.read_csv(themoviedb_data)
omdb_df = pd.read_csv(omdb_data)

In [3]:
tmdb_df.head(5)

,Unnamed: 0,Movie,Release Date,Budget,Revenue,Genres
0,0,Capote,2005-09-30,7000000,49084830,Crime
1,1,American Hustle,2013-12-12,40000000,251171807,Drama
2,2,Brokeback Mountain,2005-09-10,14000000,178043761,Drama
3,3,Walk the Line,2005-09-13,28000000,186438883,Drama
4,4,"Good Night, and Good Luck.",2005-09-16,7000000,54600000,Drama

In [4]:
omdb_df.head(5)

,Unnamed: 0,Movie,Rating,Release Date,Runtime,Metascore,IMDb Rating,Box Office,Awards,Production Company
0,0,Capote,R,03 Feb 2006,114 min,88.0,7.4,"$28,337,516",Won 1 Oscar. Another 58 wins & 86 nominations.,Sony Pictures Classics
1,1,American Hustle,R,20 Dec 2013,138 min,90.0,7.3,"$99,165,609",Nominated for 10 Oscars. Another 70 wins & 208...,Sony Pictures
2,2,Brokeback Mountain,R,13 Jan 2006,134 min,87.0,7.7,"$82,970,165",Won 3 Oscars. Another 138 wins & 128 nominations.,Focus Features
3,3,Walk the Line,PG-13,18 Nov 2005,136 min,72.0,7.9,"$119,317,827",Won 1 Oscar. Another 44 wins & 46 nominations.,20th Century Fox
4,4,"Good Night, and Good Luck.",PG,04 Nov 2005,93 min,80.0,7.5,"$31,500,000",Nominated for 6 Oscars. Another 38 wins & 121 ...,Warner Independent Pictures

In [5]:
fullquery_df = pd.merge(tmdb_df, omdb_df, on = 'Movie', how = 'right')
fullquery_df.head(2)

,Unnamed: 0_x,Movie,Release Date_x,Budget,Revenue,Genres,Unnamed: 0_y,Rating,Release Date_y,Runtime,Metascore,IMDb Rating,Box Office,Awards,Production Company
0,0.0,Capote,2005-09-30,7000000.0,49084830.0,Crime,0,R,03 Feb 2006,114 min,88.0,7.4,"$28,337,516",Won 1 Oscar. Another 58 wins & 86 nominations.,Sony Pictures Classics
1,1.0,American Hustle,2013-12-12,40000000.0,251171807.0,Drama,1,R,20 Dec 2013,138 min,90.0,7.3,"$99,165,609",Nominated for 10 Oscars. Another 70 wins & 208...,Sony Pictures

In [6]:
fullquery_df = fullquery_df[['Movie','Release Date_x','Release Date_y', 'Budget', 'Revenue', 'Box Office', 'Genres', 'Rating', 'Runtime', 'Metascore', 'IMDb Rating', 'Awards', 'Production Company']]
fullquery_df.head()

,Movie,Release Date_x,Release Date_y,Budget,Revenue,Box Office,Genres,Rating,Runtime,Metascore,IMDb Rating,Awards,Production Company
0,Capote,2005-09-30,03 Feb 2006,7000000.0,49084830.0,"$28,337,516",Crime,R,114 min,88.0,7.4,Won 1 Oscar. Another 58 wins & 86 nominations.,Sony Pictures Classics
1,American Hustle,2013-12-12,20 Dec 2013,40000000.0,251171807.0,"$99,165,609",Drama,R,138 min,90.0,7.3,Nominated for 10 Oscars. Another 70 wins & 208...,Sony Pictures
2,Brokeback Mountain,2005-09-10,13 Jan 2006,14000000.0,178043761.0,"$82,970,165",Drama,R,134 min,87.0,7.7,Won 3 Oscars. Another 138 wins & 128 nominations.,Focus Features
3,Walk the Line,2005-09-13,18 Nov 2005,28000000.0,186438883.0,"$119,317,827",Drama,PG-13,136 min,72.0,7.9,Won 1 Oscar. Another 44 wins & 46 nominations.,20th Century Fox
4,"Good Night, and Good Luck.",2005-09-16,04 Nov 2005,7000000.0,54600000.0,"$31,500,000",Drama,PG,93 min,80.0,7.5,Nominated for 6 Oscars. Another 38 wins & 121 ...,Warner Independent Pictures

In [7]:
fullquery_df.count()

Movie                 567
Release Date_x        538
Release Date_y        557
Budget                538
Revenue               538
Box Office            346
Genres                538
Rating                464
Runtime               557
Metascore             417
IMDb Rating           551
Awards                498
Production Company    465
dtype: int64

In [8]:
fullquery_df.describe()

             Budget       Revenue   Metascore  IMDb Rating
count  5.380000e+02  5.380000e+02  417.000000   551.000000
mean   3.739845e+07  1.456787e+08   72.479616     7.313430
std    5.976642e+07  2.876921e+08   14.178979     0.736059
min    0.000000e+00  0.000000e+00   27.000000     3.100000
25%    0.000000e+00  0.000000e+00   65.000000     7.000000
50%    8.700000e+06  2.312788e+07   75.000000     7.400000
75%    4.150000e+07  1.389638e+08   83.000000     7.800000
max    3.000000e+08  2.787965e+09  100.000000     9.300000

In [9]:
fullquery_df.dtypes

Movie                  object
Release Date_x         object
Release Date_y         object
Budget                float64
Revenue               float64
Box Office             object
Genres                 object
Rating                 object
Runtime                object
Metascore             float64
IMDb Rating           float64
Awards                 object
Production Company     object
dtype: object

In [10]:
fullquery_df['Box Office'] = fullquery_df['Box Office'].str.replace(',','')
fullquery_df['Box Office'] = fullquery_df['Box Office'].str.replace('$', '')
fullquery_df['Box Office'] = fullquery_df['Box Office'].fillna(0)
fullquery_df['Box Office'] = fullquery_df['Box Office'].astype(float)

In [11]:
fullquery_df.head(100)

,Movie,Release Date_x,Release Date_y,Budget,Revenue,Box Office,Genres,Rating,Runtime,Metascore,IMDb Rating,Awards,Production Company
0,Capote,2005-09-30,03 Feb 2006,7000000.0,49084830.0,28337516.0,Crime,R,114 min,88.0,7.4,Won 1 Oscar. Another 58 wins & 86 nominations.,Sony Pictures Classics
1,American Hustle,2013-12-12,20 Dec 2013,40000000.0,251171807.0,99165609.0,Drama,R,138 min,90.0,7.3,Nominated for 10 Oscars. Another 70 wins & 208...,Sony Pictures
2,Brokeback Mountain,2005-09-10,13 Jan 2006,14000000.0,178043761.0,82970165.0,Drama,R,134 min,87.0,7.7,Won 3 Oscars. Another 138 wins & 128 nominations.,Focus Features
3,Walk the Line,2005-09-13,18 Nov 2005,28000000.0,186438883.0,119317827.0,Drama,PG-13,136 min,72.0,7.9,Won 1 Oscar. Another 44 wins & 46 nominations.,20th Century Fox
4,"Good Night, and Good Luck.",2005-09-16,04 Nov 2005,7000000.0,54600000.0,31500000.0,Drama,PG,93 min,80.0,7.5,Nominated for 6 Oscars. Another 38 wins & 121 ...,Warner Independent Pictures
5,Syriana,2005-11-23,09 Dec 2005,50000000.0,93974620.0,50800000.0,Drama,R,128 min,76.0,6.9,Won 1 Oscar. Another 13 wins & 28 nominations.,Warner Bros. Pictures
6,Crash,2005-05-06,06 May 2005,6500000.0,98410061.0,55382847.0,Drama,R,112 min,69.0,7.8,Won 3 Oscars. Another 64 wins & 111 nominations.,Lions Gate Films
7,Cinderella Man,2005-06-02,03 Jun 2005,88000000.0,108539911.0,61600000.0,Romance,PG-13,144 min,69.0,8.0,Nominated for 3 Oscars. Another 16 wins & 41 n...,Universal Pictures
8,A History of Violence,2005-09-23,30 Sep 2005,32000000.0,60740827.0,31500000.0,Drama,R,96 min,81.0,7.5,Nominated for 2 Oscars. Another 37 wins & 78 n...,New Line Cinema
9,Mrs Henderson Presents,2005-09-08,17 Feb 2006,0.0,0.0,10965943.0,Comedy,R,103 min,71.0,7.1,Nominated for 2 Oscars. Another 6 wins & 31 no...,Weinstein Company
10,Transamerica,2005-12-23,03 Mar 2006,1000000.0,13350369.0,8713873.0,Drama,R,103 min,66.0,7.4,Nominated for 2 Oscars. Another 32 wins & 23 n...,Weinstein Company
11,Pride,2014-09-12,12 Sep 2014,0.0,7523634.0,0.0,Drama,R,119 min,79.0,7.8,Nominated for 1 Golden Globe. Another 9 wins &...,CBS Films
12,North Country,2005-02-12,21 Oct 2005,35000000.0,25224242.0,18324242.0,Drama,R,126 min,68.0,7.3,Nominated for 2 Oscars. Another 6 wins & 17 no...,Warner Bros. Pictures
13,Junebug,2005-08-03,16 Sep 2005,1000000.0,0.0,2416555.0,Comedy,R,106 min,80.0,7.0,Nominated for 1 Oscar. Another 21 wins & 27 no...,Sony Pictures Classics
14,The Constant Gardener,2005-08-31,31 Aug 2005,25000000.0,82466670.0,33565375.0,Drama,R,129 min,82.0,7.4,Won 1 Oscar. Another 35 wins & 68 nominations.,Focus Features
15,Being George Clooney,2016-02-06,15 Oct 2016,0.0,0.0,0.0,Documentary,NaN,88 min,NaN,6.7,1 nomination.,NaN
16,Little Italy,2018-08-24,21 Sep 2018,0.0,0.0,0.0,Comedy,NaN,102 min,28.0,5.7,NaN,Lionsgate
17,Made in France,2015-10-27,23 Sep 2016,0.0,0.0,0.0,Drama,R,89 min,NaN,6.2,NaN,NaN
18,A John Williams Celebration,2015-06-15,30 Jun 2015,0.0,0.0,0.0,Music,NOT RATED,103 min,NaN,8.5,NaN,NaN
19,Blood Diamond,2006-12-07,08 Dec 2006,100000000.0,170877916.0,57300000.0,Drama,R,143 min,64.0,8.0,Nominated for 5 Oscars. Another 8 wins & 26 no...,Warner Bros. Pictures
20,Half Nelson,2006-08-11,22 Sep 2006,700000.0,4911725.0,2591047.0,Drama,R,106 min,85.0,7.2,Nominated for 1 Oscar. Another 29 wins & 47 no...,ThinkFilm
21,Venus,2006-09-02,16 Feb 2007,0.0,0.0,3261449.0,Comedy,R,95 min,82.0,7.1,Nominated for 1 Oscar. Another 4 wins & 20 nom...,Miramax Films
22,The Pursuit of Happyness,2006-12-14,15 Dec 2006,55000000.0,307077295.0,162586036.0,Drama,PG-13,117 min,64.0,8.0,Nominated for 1 Oscar. Another 11 wins & 24 no...,Sony Pictures
23,The Last King of Scotland,2006-09-01,19 Jan 2007,6000000.0,48027970.0,17449410.0,Drama,R,123 min,74.0,7.7,Won 1 Oscar. Another 47 wins & 31 nominations.,Fox Searchlight
24,Little Miss Sunshine,2006-07-26,18 Aug 2006,8000000.0,100523181.0,59831476.0,Comedy,R,101 min,80.0,7.8,Won 2 Oscars. Another 68 wins & 107 nominations.,Fox Searchlight
25,Little Children,2006-10-06,09 Feb 2007,26000000.0,14821658.0,5307219.0,Romance,R,136 min,75.0,7.5,Nominated for 3 Oscars. Another 20 wins & 57 n...,New Line Cinema
26,Dreamgirls,2006-12-25,25 Dec 2006,70000000.0,154937680.0,103300000.0,Drama,PG-13,130 min,76.0,6.5,Won 2 Oscars. Another 66 wins & 91 nominations.,Dreamworks
27,The Departed,2006-10-05,06 Oct 2006,90000000.0,289847354.0,132300000.0,Drama,R,151 min,85.0,8.5,Won 4 Oscars. Another 92 wins & 135 nominations.,Warner Bros. Pictures
28,Volver,2006-03-16,26 Jan 2007,12899867.0,85582407.0,12830604.0,Comedy,R,121 min,84.0,7.6,Nominated for 1 Oscar. Another 60 wins & 90 no...,Sony Pictures Classics
29,Notes on a Scandal,2006-12-25,26 Jan 2007,15000000.0,49469904.0,17400000.0,Drama,R,92 min,73.0,7.4,Nominated for 4 Oscars. Another 15 wins & 68 n...,Fox Searchlight Pictures
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Last Days,2005-05-13,13 May 2005,0.0,1928985.0,356500.0,Drama,R,97 min,67.0,5.8,1 win & 5 nominations.,Picture House
71,Sunshine,2007-04-05,27 Jul 2007,50000000.0,32017803.0,0.0,Science Fiction,R,107 min,64.0,7.3,1 win & 18 nominations.,NaN
72,A Christmas Carol,1938-12-16,06 Nov 2009,0.0,0.0,137816456.0,Drama,PG,96 min,55.0,6.8,3 wins & 5 nominations.,Walt Disney Studios
73,iCarly: iGo to Japan,2008-11-08,08 Nov 2008,0.0,0.0,0.0,Comedy,TV-G,71 min,NaN,6.4,NaN,NaN
74,One Heart: The A.R. Rahman Concert Film,2017-09-01,08 Sep 2017,0.0,0.0,0.0,Music,NaN,87 min,NaN,8.9,NaN,NaN
75,Crazy Heart,2009-12-16,05 Feb 2010,7000000.0,47405566.0,38349555.0,Drama,R,112 min,83.0,7.3,Won 2 Oscars. Another 36 wins & 29 nominations.,Fox Searchlight Pictures
76,Up in the Air,2009-09-05,23 Dec 2009,25000000.0,163670000.0,83775048.0,Drama,R,109 min,83.0,7.4,Nominated for 6 Oscars. Another 76 wins & 158 ...,Paramount Pictures
77,A Single Man,2009-10-19,05 Feb 2010,7000000.0,24964890.0,9098668.0,Romance,R,99 min,77.0,7.6,Nominated for 1 Oscar. Another 36 wins & 55 no...,The Weinstein Company
78,Invictus,2009-12-10,11 Dec 2009,60000000.0,122233971.0,37431431.0,Drama,PG-13,134 min,74.0,7.3,Nominated for 2 Oscars. Another 10 wins & 33 n...,Warner Bros. Pictures
79,The Hurt Locker,2008-10-10,31 Jul 2009,15000000.0,42000000.0,15700000.0,Drama,R,131 min,94.0,7.6,Won 6 Oscars. Another 117 wins & 126 nominations.,Summit Entertainment
80,The Messenger,2009-11-13,04 Dec 2009,6500000.0,1521261.0,1006655.0,Drama,R,113 min,77.0,7.1,Nominated for 2 Oscars. Another 17 wins & 44 n...,Oscilloscope Pictures
81,The Last Station,2009-09-04,26 Feb 2010,0.0,0.0,6500000.0,Drama,R,112 min,76.0,7.0,Nominated for 2 Oscars. Another 3 wins & 15 no...,Sony Pictures Classics
82,The Lovely Bones,2009-12-26,15 Jan 2010,65000000.0,93525586.0,43982842.0,Fantasy,PG-13,135 min,42.0,6.7,Nominated for 1 Oscar. Another 10 wins & 45 no...,Paramount Pictures
83,Inglourious Basterds,2009-08-18,21 Aug 2009,70000000.0,319131050.0,120523073.0,Drama,R,153 min,69.0,8.3,Won 1 Oscar. Another 129 wins & 165 nominations.,The Weinstein Company
84,The Blind Side,2009-11-20,20 Nov 2009,29000000.0,309208309.0,255900000.0,Drama,PG-13,129 min,53.0,7.7,Won 1 Oscar. Another 7 wins & 30 nominations.,Warner Bros. Pictures
85,An Education,2009-10-29,05 Feb 2010,7500000.0,26096852.0,12512069.0,Drama,PG-13,100 min,85.0,7.3,Nominated for 3 Oscars. Another 35 wins & 91 n...,Sony Classics
86,Precious,2009-11-06,20 Nov 2009,10000000.0,47536959.0,47536959.0,Drama,R,110 min,79.0,7.3,Won 2 Oscars. Another 111 wins & 98 nominations.,Lionsgate Films
87,Nine,2009-12-03,25 Dec 2009,80000000.0,53825515.0,19628665.0,Drama,PG-13,118 min,49.0,5.8,Nominated for 4 Oscars. Another 8 wins & 56 no...,The Weinstein Co.
88,Titanic: The Final Word with James Cameron,2012-04-08,08 Apr 2012,0.0,0.0,0.0,Documentary,NaN,120 min,NaN,7.7,NaN,NaN
89,Quentin Tarantino: 20 Years of Filmmaking,2012-11-20,20 Nov 2012,0.0,0.0,0.0,Documentary,NaN,125 min,NaN,7.1,NaN,NaN
90,The Butler,2013-08-16,16 Mar 2017,25000000.0,115922175.0,0.0,Drama,NaN,70 min,NaN,7.6,NaN,NaN
91,Imagining Argentina,2003-09-13,16 Apr 2004,0.0,0.0,0.0,Drama,R,107 min,27.0,6.3,1 nomination.,Arenas Entertainment
92,Hans Zimmer: Live in Prague,2017-10-01,03 Nov 2017,0.0,0.0,0.0,Music,NOT RATED,150 min,NaN,9.1,NaN,NaN
93,Biutiful,2010-10-20,04 Feb 2011,0.0,25147786.0,5100937.0,Drama,R,148 min,58.0,7.5,Nominated for 2 Oscars. Another 18 wins & 45 n...,Roadside Attractions
94,True Grit,2010-12-22,22 Dec 2010,38000000.0,252276927.0,171031347.0,Drama,PG-13,110 min,80.0,7.6,Nominated for 10 Oscars. Another 37 wins & 153...,Paramount Pictures
95,The Social Network,2010-10-01,01 Oct 2010,40000000.0,224920315.0,96400000.0,Drama,PG-13,120 min,95.0,7.7,Won 3 Oscars. Another 165 wins & 168 nominations.,Columbia Pictures
96,The King's Speech,2010-09-06,25 Dec 2010,15000000.0,414211549.0,138300000.0,Drama,R,118 min,88.0,8.0,Won 4 Oscars. Another 102 wins & 194 nominations.,The Weinstein Company
97,127 Hours,2010-11-05,28 Jan 2011,18000000.0,35692920.0,18329466.0,Adventure,R,94 min,82.0,7.6,Nominated for 6 Oscars. Another 23 wins & 141 ...,Fox Searchlight
98,The Fighter,2010-12-17,17 Dec 2010,25000000.0,93617009.0,93571803.0,Drama,R,116 min,79.0,7.8,Won 2 Oscars. Another 72 wins & 116 nominations.,Paramount Pictures
99,Winter's Bone,2010-06-11,16 Jul 2010,2000000.0,13831503.0,6200000.0,Drama,R,100 min,90.0,7.2,Nominated for 4 Oscars. Another 63 wins & 120 ...,Roadside Attractions

In [12]:
fullquery_df.dtypes

Movie                  object
Release Date_x         object
Release Date_y         object
Budget                float64
Revenue               float64
Box Office            float64
Genres                 object
Rating                 object
Runtime                object
Metascore             float64
IMDb Rating           float64
Awards                 object
Production Company     object
dtype: object

In [13]:
fullquery_df['Runtime'] = fullquery_df['Runtime'].str.replace(' min','')
fullquery_df['Runtime'] = fullquery_df['Runtime'].fillna(0)
fullquery_df['Runtime'] = fullquery_df['Runtime'].astype(float)
fullquery_df.head()

,Movie,Release Date_x,Release Date_y,Budget,Revenue,Box Office,Genres,Rating,Runtime,Metascore,IMDb Rating,Awards,Production Company
0,Capote,2005-09-30,03 Feb 2006,7000000.0,49084830.0,28337516.0,Crime,R,114.0,88.0,7.4,Won 1 Oscar. Another 58 wins & 86 nominations.,Sony Pictures Classics
1,American Hustle,2013-12-12,20 Dec 2013,40000000.0,251171807.0,99165609.0,Drama,R,138.0,90.0,7.3,Nominated for 10 Oscars. Another 70 wins & 208...,Sony Pictures
2,Brokeback Mountain,2005-09-10,13 Jan 2006,14000000.0,178043761.0,82970165.0,Drama,R,134.0,87.0,7.7,Won 3 Oscars. Another 138 wins & 128 nominations.,Focus Features
3,Walk the Line,2005-09-13,18 Nov 2005,28000000.0,186438883.0,119317827.0,Drama,PG-13,136.0,72.0,7.9,Won 1 Oscar. Another 44 wins & 46 nominations.,20th Century Fox
4,"Good Night, and Good Luck.",2005-09-16,04 Nov 2005,7000000.0,54600000.0,31500000.0,Drama,PG,93.0,80.0,7.5,Nominated for 6 Oscars. Another 38 wins & 121 ...,Warner Independent Pictures

In [14]:
fullquery_df.dtypes

Movie                  object
Release Date_x         object
Release Date_y         object
Budget                float64
Revenue               float64
Box Office            float64
Genres                 object
Rating                 object
Runtime               float64
Metascore             float64
IMDb Rating           float64
Awards                 object
Production Company     object
dtype: object

In [15]:
fullquery_df.to_csv('OMDB_TMDB_DataMerged.csv')